services:
  mysql:
    image: mysql:8
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CollegeDB
    ports:
      - 3306:3306
    options: >-
      --health-cmd="mysqladmin ping -h localhost -uroot -proot"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=10
